<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{CCAFS Amazon S3 Keys}
%\VignetteEncoding{UTF-8}
-->

```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  fig.path = "img/"
)
```

CCAFS Amazon S3 Keys
====================

Keys used in this package are a bit opaque. To make it a bit more clear how
keys link to the CCAFS web interface, the following is an example run through 
the website to show you how a key is found. 

1. Navigate to <http://ccafs-climate.org/>
2. Navigate to Data -> Spatial Downscaling
3. On the left bar -> File Set, select "Delta Method IPCC AR5" under the 
"Empirical/Statistical Downscaling"
4. On the left bar -> Scenario, select "RCP 2.6"
5. On the left bar -> Model, select the "bcc_csm1_1_m"
6. On the top bar -> Extent, select "Global"
7. On the top bar -> Format, select "ASCII Grid Format"
8. On the top bar -> Period, select "2030s"
9. On the top bar -> Variable, select "Precipitation"
10. On the top bar -> Resolution, select "10 minutes"
11. Click "Search"
12. Click the box next to the file returned by the search, and clicked "Generate Download Links"
13. Select "Skip", or fill in your information
14. Copy the address of the file to download (Right click -> Copy Link Address)
15. Assign the link address as a character string, removing the `http://cgiardata.s3.amazonaws.com/` (e.g., `http://cgiardata.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2030s/bcc_csm1_1_m/10min/bcc_csm1_1_m_rcp2_6_2030s_prec_10min_r1i1p1_no_tile_asc.zip` changes to `ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2030s/bcc_csm1_1_m/10min/bcc_csm1_1_m_rcp2_6_2030s_prec_10min_r1i1p1_no_tile_asc.zip`). 
16. Use the key as input to `cc_data_fetch()`
